### ISSUE TITLE
Suggestions for syntax

### ISSUE THREAD

**Issue by belozer** [tadatuta/bem-indent-syntax#11]
Example:

```
 header *type_main *view_list +b2 +b4 *type_list
```

```
{
  block: "header",
  mods: {
    type: "main",
    view: "list"
  },
  mix: [
    {
      block: "b2"
    },
    {
      block: "b4",
      mods: {
        type: "list"
      }
    },
  ]
}
```

**Comment by vithar** [comment]
_type_main

**Comment by tadatuta** [comment]
@belozyorcev уже сейчас можно не указывать родительский блок и плюсы не нужны, спейса достататочно:

```
 header _type_main _view_list b2 b4
```

А вот с последним `_type_list` обнаружился баг. Починю в рамках этого тикета.

**Comment by belozer** [comment]
@tadatuta визуально  `*` лучше отделяет модификаторы, чем пробел `header *type_main *view_list b2 b4`.

**Comment by tadatuta** [comment]
Идея в том, что можно использовать ровно те же символы-разделители, что в классах и на файловой системе.

Т.е. по умолчанию будет  `_m1_v1` для модификаторов и `__e1` для элементов, но можно сконфигурировать произвольные разделители для проекта в терминах `bem-naming` и использовать их.
